DROP TABLE IF EXISTS USER_PROFILE;  
CREATE TABLE USER_PROFILE (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
user_name VARCHAR(50) NOT NULL,  
password VARCHAR(150) NOT NULL,
role VARCHAR(50) NOT NULL
);
--password
INSERT INTO USER_PROFILE(user_name, password, role) VALUES ('admin', '$2a$10$5vWD8A/p6kFFuZh5C8t6Re205rufaVh8c6RUe/S6Vl39.3pvFojae', 'ROLE_ADMIN');